import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const base = process.env.TEST_URL || 'http://localhost:4324';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const errors = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
try {
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.waitForFunction(() => document.documentElement.classList.contains('motion-ready'));
  await page.waitForTimeout(1000);
  assert.equal(await page.locator('#hero-title').evaluate(el => getComputedStyle(el).opacity), '1');
  assert.ok(await page.locator('[data-reveal]').count() > 20);
  assert.ok(await page.locator('.subtle-parallax').count() <= 2);
  const heading = page.locator('#selection .section-heading');
  await heading.scrollIntoViewIfNeeded();
  await page.waitForFunction(() => document.querySelector('#selection .section-heading')?.classList.contains('is-visible'));
  await page.waitForTimeout(900);
  assert.equal(await heading.locator('h2').evaluate(el => getComputedStyle(el).opacity), '1');
  assert.equal(await heading.evaluate(el => getComputedStyle(el, '::before').transform), 'matrix(1, 0, 0, 1, 0, 0)');
  await page.locator('#selection .project-image').first().scrollIntoViewIfNeeded();
  await page.waitForTimeout(900);
  await page.locator('#selection .project-image').first().hover();
  await page.waitForTimeout(550);
  const scale = await page.locator('#selection .project-image img').first().evaluate(el => new DOMMatrixReadOnly(getComputedStyle(el).transform).a);
  assert.ok(scale >= 1 && scale <= 1.0201);
  await page.locator('#selection .project-image').first().click();
  await page.waitForURL('**/projects/habitat-de-a-a-z/');
  await page.waitForTimeout(1000);
  assert.equal(await page.locator('h1').textContent(), 'Habitat from A to Z');
  const gallery = page.getByRole('button', { name: 'Enlarge : Site analysis', exact: true });
  await gallery.scrollIntoViewIfNeeded(); await page.waitForTimeout(900); await gallery.click();
  await page.waitForFunction(() => document.querySelector('dialog')?.open);
  await page.keyboard.press('Escape'); assert.equal(await page.locator('dialog').evaluate(el => el.open), false);
  await page.locator('.back-link').click(); await page.waitForURL('**/projects/');
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.waitForTimeout(1000);
  await page.locator('.hero-visual').click(); await page.waitForURL('**/projects/habitat-de-a-a-z/');
  await page.waitForTimeout(900);
  assert.equal(await page.locator('.detail-hero img').evaluate(el => getComputedStyle(el).viewTransitionName === 'selected-project-image'), false);
  console.log('Desktop: reveal, lines, restrained hover, two shared-image navigations and gallery PASS');

  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.waitForTimeout(600);
  assert.equal(await page.locator('.subtle-parallax').count(), 0);
  await page.locator('.menu-toggle').click();
  assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'true');
  await page.keyboard.press('Escape'); assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'false');
  await page.locator('.menu-toggle').click();
  await page.locator('#main-nav a[href="/contact/"]').click(); await page.waitForURL('**/contact/');
  await page.waitForTimeout(600);
  await page.locator('.menu-toggle').click(); assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'), 'true');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  console.log('Mobile: staggered menu, repeated SPA setup, Escape and no parallax PASS');

  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto(base, { waitUntil: 'networkidle' });
  assert.equal(await page.locator('.subtle-parallax').count(), 0);
  const hidden = await page.locator('[data-reveal]').evaluateAll(elements => elements.filter(el => {
    const style = getComputedStyle(el); return style.opacity !== '1' || style.transform !== 'none' || style.clipPath !== 'none';
  }).length);
  assert.equal(hidden, 0);
  assert.equal(await page.evaluate(() => document.getAnimations().filter(animation => animation.playState === 'running').length), 0);
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForTimeout(100);
  assert.equal(await page.locator('.subtle-parallax').count(), 0);
  assert.equal(await page.locator('[data-reveal]:not(.is-visible)').count(), 0);
  assert.deepEqual(errors, []);
  console.log('Reduced motion on load and live change: all content immediate, no animation, no console errors PASS');

  const plain = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 1440, height: 1000 } });
  const noJS = await plain.newPage(); await noJS.goto(base);
  assert.equal(await noJS.locator('#hero-title').evaluate(el => getComputedStyle(el).opacity), '1');
  assert.equal(await noJS.locator('.project-image').first().evaluate(el => getComputedStyle(el).opacity), '1');
  await plain.close(); console.log('Content remains visible without JavaScript PASS');
} finally { await browser.close(); }
